version: "3.9"

services:
  app:
    container_name: Django
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./hackathonbasic:/code
    ports: # 内部通信用ポート
      - "8000"
    working_dir: /code
    environment: # SessionManagerにて手動でEC2に環境変数を設定したものをコンテナにも設定
      - DB_NAME
      - DB_USER
      - DB_PASSWORD
      - DB_HOST
      - DB_PORT
    command: bash -c "python3 manage.py runserver 0.0.0.0:8000"

  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "80:80" # 外部からアクセスする80番ポートを公開
    volumes: # ローカルのnginx.confをコンテナ内のnginx.confにマウント
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
