# Generated by Django 3.2 on 2024-12-21 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_auto_20241221_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.TextField(choices=[('business', 'ビジネス'), ('life', '生活'), ('ohter', 'その他')], default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='text',
            field=models.TextField(max_length=255),
        ),
    ]
