# Generated by Django 3.2 on 2024-12-21 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_auto_20241221_0903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='category',
            field=models.TextField(choices=[('business', 'ビジネス'), ('life', '生活'), ('other', 'その他')], max_length=100),
        ),
    ]
